--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2026-07-14 09:27:59

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16691)
-- Name: granted_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.granted_permission (
    id bigint NOT NULL,
    operation_id bigint,
    role_id bigint
);


ALTER TABLE public.granted_permission OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16690)
-- Name: granted_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.granted_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.granted_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16697)
-- Name: module; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.module (
    id bigint NOT NULL,
    base_path character varying(255),
    name character varying(255)
);


ALTER TABLE public.module OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16696)
-- Name: module_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16705)
-- Name: operation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operation (
    permit_all boolean NOT NULL,
    id bigint NOT NULL,
    module_id bigint,
    http_method character varying(255),
    name character varying(255),
    path character varying(255)
);


ALTER TABLE public.operation OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16704)
-- Name: operation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16752)
-- Name: reservations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    end_date timestamp(6) without time zone,
    start_date timestamp(6) without time zone,
    status character varying(255),
    total_amount numeric(38,2),
    total_hours integer,
    updated_at timestamp(6) without time zone,
    space_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_PAYMENT'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.reservations OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16751)
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16713)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16712)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16759)
-- Name: spaces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.spaces (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone,
    hourly_rate numeric(38,2) NOT NULL,
    location character varying(150) NOT NULL,
    name character varying(20) NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT spaces_type_check CHECK (((type)::text = ANY ((ARRAY['MEETING_ROOM'::character varying, 'OPEN_DESK'::character varying, 'PRIVATE_OFFICE'::character varying, 'CONFERENCE_ROOM'::character varying])::text[])))
);


ALTER TABLE public.spaces OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16758)
-- Name: spaces_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.spaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16719)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    enabled boolean,
    id bigint NOT NULL,
    role_id bigint,
    name character varying(150) NOT NULL,
    password character varying(200) NOT NULL,
    username character varying(200) NOT NULL,
    email character varying(300)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16718)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4897 (class 0 OID 16691)
-- Dependencies: 218
-- Data for Name: granted_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.granted_permission (id, operation_id, role_id) FROM stdin;
1	1	1
2	2	1
4	3	1
5	4	1
6	5	1
7	6	1
8	7	1
9	5	2
10	8	2
11	8	1
14	10	1
15	11	2
16	12	1
13	9	1
17	13	1
18	13	2
19	14	1
20	14	2
21	15	1
22	15	2
23	16	1
24	16	2
25	17	1
26	17	2
\.


--
-- TOC entry 4899 (class 0 OID 16697)
-- Dependencies: 220
-- Data for Name: module; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.module (id, base_path, name) FROM stdin;
1	/user	USER
2	/auth	AUTH
3	/spaces	SPACES
4	/reservations	RESERVATION
5	/mock-payment	MOCK_PAYMENT
6	/actuator	ACTUATOR
7	/swagger-ui	SWAGGER
8	/v3	OPEN_API
\.


--
-- TOC entry 4901 (class 0 OID 16705)
-- Dependencies: 222
-- Data for Name: operation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operation (permit_all, id, module_id, http_method, name, path) FROM stdin;
t	1	1	POST	CREATE_USER	
t	2	2	POST	AUTHENTICATE	/authenticate
f	3	3	POST	CREATE_SPACE	
f	4	3	GET	GET_ALL_SPACES	
f	5	3	GET	GET_SPACE	/[0-9]*
f	6	3	PUT	UPDATE_SPACE	/[0-9]*
f	7	3	DELETE	DELETE_SPACE	/[0-9]*
f	8	4	POST	CREATE_RESERVATION	
f	9	4	GET	GET_ALL_RESERVATIONS	
f	10	4	GET	GET_RESERVATION	/[0-9]*
f	11	4	GET	GET_MY_RESERVATION	/my
f	12	4	PATCH	CANCEL_RESERVATION	/[0-9]*/cancel
t	13	5	POST	VALIDATE_MOCK_PAYMENT	/validate
t	14	6	GET	ACTUATOR_HEALTH	/health
t	15	6	GET	ACTUATOR_METRICS	/metrics
t	17	8	GET	OPEN_API_DOCS	/api-docs.*
t	16	7	GET	SWAGGER	/index.html
t	18	7	GET	SWAGGER	/error
t	19	8	GET	OPEN_API_DOCS_ERROR	/error
\.


--
-- TOC entry 4907 (class 0 OID 16752)
-- Dependencies: 228
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservations (id, created_at, end_date, start_date, status, total_amount, total_hours, updated_at, space_id, user_id) FROM stdin;
5	2026-07-13 00:38:57.446466	2026-07-15 11:00:00	2026-07-15 10:00:00	CANCELLED	25.50	1	2026-07-13 11:01:47.437183	2	2
6	2026-07-13 11:03:31.742099	2026-07-15 11:00:00	2026-07-15 10:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
7	2026-07-13 16:15:42.206441	2026-07-15 12:00:00	2026-07-15 11:00:00	CONFIRMED	25.50	1	\N	2	2
8	2026-07-13 21:42:06.383265	2026-07-15 13:00:00	2026-07-15 12:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
9	2026-07-13 21:49:19.995241	2026-07-15 14:00:00	2026-07-15 13:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
10	2026-07-13 21:59:04.021933	2026-07-15 15:00:00	2026-07-15 14:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
11	2026-07-13 22:07:00.484878	2026-07-15 16:00:00	2026-07-15 15:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
12	2026-07-13 22:19:22.36951	2026-07-15 17:00:00	2026-07-15 16:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
13	2026-07-13 22:32:02.489582	2026-07-15 18:00:00	2026-07-15 17:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
14	2026-07-13 22:34:31.281823	2026-07-15 19:00:00	2026-07-15 18:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
15	2026-07-13 22:39:35.128819	2026-07-15 20:00:00	2026-07-15 19:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
16	2026-07-13 22:41:30.003417	2026-07-15 21:00:00	2026-07-15 20:00:00	PENDING_PAYMENT	25.50	1	\N	2	2
17	2026-07-13 22:43:10.721109	2026-07-15 22:00:00	2026-07-15 21:00:00	CONFIRMED	25.50	1	\N	2	2
\.


--
-- TOC entry 4903 (class 0 OID 16713)
-- Dependencies: 224
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role (id, name) FROM stdin;
1	ADMIN
2	USER
\.


--
-- TOC entry 4909 (class 0 OID 16759)
-- Dependencies: 230
-- Data for Name: spaces; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spaces (id, capacity, created_at, hourly_rate, location, name, type, updated_at) FROM stdin;
2	10	\N	25.50	Edificio Torre Futura, Nivel 5, San Salvador	Sala Alpha	MEETING_ROOM	\N
\.


--
-- TOC entry 4905 (class 0 OID 16719)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (enabled, id, role_id, name, password, username, email) FROM stdin;
t	1	1	daniel larin	$2a$10$6WOq0nv.YTM0OstLUHTTP.iRbIMAkFkJQujiP0NyYo9SEnSZI/jIC	danKaos	\N
t	2	2	Juan Perez	$2a$10$Xe6JBZEvbrZn1t8bZsxcpe0Na/Q9HrQf8wYp1Yw5LMN2ui2HYGxMq	juanjo	\N
\.


--
-- TOC entry 4915 (class 0 OID 0)
-- Dependencies: 217
-- Name: granted_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.granted_permission_id_seq', 26, true);


--
-- TOC entry 4916 (class 0 OID 0)
-- Dependencies: 219
-- Name: module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.module_id_seq', 8, true);


--
-- TOC entry 4917 (class 0 OID 0)
-- Dependencies: 221
-- Name: operation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operation_id_seq', 19, true);


--
-- TOC entry 4918 (class 0 OID 0)
-- Dependencies: 227
-- Name: reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservations_id_seq', 17, true);


--
-- TOC entry 4919 (class 0 OID 0)
-- Dependencies: 223
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 2, true);


--
-- TOC entry 4920 (class 0 OID 0)
-- Dependencies: 229
-- Name: spaces_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.spaces_id_seq', 2, true);


--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 4728 (class 2606 OID 16695)
-- Name: granted_permission granted_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.granted_permission
    ADD CONSTRAINT granted_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 16703)
-- Name: module module_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.module
    ADD CONSTRAINT module_pkey PRIMARY KEY (id);


--
-- TOC entry 4732 (class 2606 OID 16711)
-- Name: operation operation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_pkey PRIMARY KEY (id);


--
-- TOC entry 4742 (class 2606 OID 16757)
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- TOC entry 4734 (class 2606 OID 16717)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4744 (class 2606 OID 16764)
-- Name: spaces spaces_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);


--
-- TOC entry 4736 (class 2606 OID 16729)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4738 (class 2606 OID 16725)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4740 (class 2606 OID 16727)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4748 (class 2606 OID 16745)
-- Name: users fk4qu1gr772nnf6ve5af002rwya; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk4qu1gr772nnf6ve5af002rwya FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- TOC entry 4749 (class 2606 OID 16765)
-- Name: reservations fkamig3ih2d03a4kb15cuoax1rm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkamig3ih2d03a4kb15cuoax1rm FOREIGN KEY (space_id) REFERENCES public.spaces(id);


--
-- TOC entry 4750 (class 2606 OID 16770)
-- Name: reservations fkb5g9io5h54iwl2inkno50ppln; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4745 (class 2606 OID 16730)
-- Name: granted_permission fkganyk3x2gfy9mfw9j1itc10v8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.granted_permission
    ADD CONSTRAINT fkganyk3x2gfy9mfw9j1itc10v8 FOREIGN KEY (operation_id) REFERENCES public.operation(id);


--
-- TOC entry 4746 (class 2606 OID 16735)
-- Name: granted_permission fkm4v6hvxf7972y0liwhbfe7x6a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.granted_permission
    ADD CONSTRAINT fkm4v6hvxf7972y0liwhbfe7x6a FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- TOC entry 4747 (class 2606 OID 16740)
-- Name: operation fksjnvlggb9dhyg5upt7gn2nuew; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT fksjnvlggb9dhyg5upt7gn2nuew FOREIGN KEY (module_id) REFERENCES public.module(id);


-- Completed on 2026-07-14 09:27:59

--
-- PostgreSQL database dump complete
--

