services:

  postgres:
    image: postgres:17
    container_name: gestion-reserva-db
    environment:
      POSTGRES_DB: GestionReserva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup/GestionReserva_plain.sql:/docker-entrypoint-initdb.d/GestionReserva.sql


  app:
    build: .
    container_name: gestion-reserva-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker


volumes:
  postgres_data: