spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionReserva
spring.datasource.username=postgres
spring.datasource.password=1lovemore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/api/v1

user.not.found=User not found
role.not.found=Role not found
security.default.role=ADMIN
product.not.found=Product not found
security.jwt.expiration-in-minutes=30
security.jwt.secret-key=bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn



# ==========================
# RESILIENCE4J
# ==========================

resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true

# ==========================
# ACTUATOR
# ==========================

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
info.app.name=Coworking Reservation API
info.app.description=Backend reservation management service
info.app.version=1.0.0