spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://postgres:5432/GestionReserva
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Coworking Reservation API
    description: Backend reservation management service
    version: 1.0.0