spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/GestionReserva
spring.datasource.username=postgres
spring.datasource.password=1lovemore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/api/v1

user.not.found=User not found
role.not.found=Role not found
security.default.role=ADMIN
product.not.found=Product not found
security.jwt.expiration-in-minutes=30
security.jwt.secret-key=bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn